config/routes.rb
Rails.application.routes.draw do

  root 'listings#index'
  
  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates_presence_of :description
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  puts "test"
end
# test

app/controllers/listings_controller.rb
class ListingsController< ApplicationController
  
  def index 
    @listings = Listing.all
  end
  
  def new
    @listing = Listing.new
  end
  
  def create
    binding.pry
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to listings_path
    else
      render 'new'
    end
  end
  
  private 
  def listing_params
    params.require(:listing).permit(:description)
    puts 'test'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/index.html.erb
<h1>Todo's</h1>

<% @listings.each do |listing| %>
  <ul>
    <li><%= listing.description %></li>
  </ul>
  

<% end %>

<%= link_to "Create a new todo", new_listing_path %>

app/views/listings/new.html.erb
<h1>Add a new Todo</h1>
<% if@listing.errors.any? %>
  <h2>There was an error in your submission</h2>
  <ul>
    <% @listing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @listing do |f| %>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.submit "submit todo" %>
  </p>
<% end %>